export const SELECT_CARD = 'SELECT_CARD';
export const RESET_SELECTION = 'RESET_SELECTION';
export const TOGGLE_CARD_SELECTION = 'TOGGLE_CARD_SELECTION';
export const END_GAME = 'END_GAME';
export const START_GAME = 'START_GAME';
export const GENERATE_CARDS = 'GENERATE_CARDS';
export const TOGGLE_CARD_REVEAL = 'TOGGLE_CARD_REVEAL';
export const UPDATE_PAIR = 'UPDATE_PAIR';
export const RESET_CARD_STATUS = 'RESET_CARD_STATUS';

export const INCREMENT_CARD_FLIPS = 'INCREMENT_CARD_FLIPS';
export const RESET_CARD_FLIPS = 'RESET_CARD_FLIPS';
export const INCREMENT_SCORE = 'INCREMENT_SCORE';
export const RESET_SCORE = 'RESET_SCORE';
export const UPDATE_ACTION_HISTORY = 'UPDATE_ACTION_HISTORY';
export const RESET_ACTION_HISTORY = 'RESET_ACTION_HISTORY';

export const DECREMENT_COUNTDOWN = 'DECREMENT_COUNTDOWN';
export const RESET_COUNTDOWN = 'RESET_COUNTDOWN';
export const INCREMENT_TIME = 'INCREMENT_TIME';
export const RESET_TIME = 'RESET_TIME';

export const ADD_SCORE = 'ADD_SCORE';
export const SORT_SCORES = 'SORT_SCORES';
export const PLAY_HISTORY = 'PLAY_HISTORY';
export const TOGGLE_REPLAY = 'TOGGLE_REPLAY';